name: Azure Role Assignment

on:
  workflow_dispatch:  # Trigger manually via GitHub UI

jobs:
  assign-roles:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Azure CLI
      uses: azure/CLI@v1

    - name: Run Role Assignment Script
      run: |
        pwsh ./PECWithAdminAgents/test.ps1